### ISSUE TITLE
Documentation for clj/cljs implementation for websockets

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#16]

**Comment by VikramShawFL** [comment]
How do you want the documentation to be? Like aboves the codes using comments or a separate folder for the documentation

**Comment by azureus89** [comment]
make a docs folder

**Comment by VikramShawFL** [comment]
In doc folder it will have codes which I have added in project.clj and src right

**Comment by azureus89** [comment]
Yes you should add code snippets in the documentation to make your point clear

**Comment by azureus89** [comment]
In the actual code also add a little documentation .. like function descriptions

**Comment by VikramShawFL** [comment]
In project.clj I have added and in src still needs to be add

**Comment by azureus89** [comment]
Just a note on how you run a clj + cljs project that has websockets:

1. Start the http-kit webserver by
a) Using lein run : this should work automatically, but any edits to the routes wont have effect
b) Using cider-jack-in : When you start the repl, all the code has loaded, but the server hasnt started yet, in order to start the server you have to go into the repl and run `(-main)` or whatever the main function is in your program that starts the app server. After this it works just like lein run, except when you change routing etc, it will update.

2. Compiling clojurescript
Start figwheel cider-jack-in-cljs ... this will compile your clojurescript code into js. The javascript goes into your output folder. While the clojurescript server is running, using figwheel you will be able to auto update. Even after you close the fighweel repl though the application will continue to work, this is because the last compiled js is still there in the output folder. You dont NEED the clojurescript server running in order for the application to work .. you need it running in order to continue to make edits on your front end. But the clojurescript code NEEDS lein run or the cider-jack-in method above to work first, because without that there is no running websocket server.

**Comment by azureus89** [comment]
Please document all this properly in the documentation you are submitting in this branch

**Comment by azureus89** [comment]
@VikramShawFL not entirely happy with the documentation ... im keeping this issue open because im not sure if @ParikshithMohan @kattakavya  will know how to use this project from the documentation alone ... I urge you guys to please post here if you have any issues getting the project running and everything working. I don't want you to figure it out ... I want you to use this opportunity to point out holes in the documentation so that vikram can improve it.

**Comment by VikramShawFL** [comment]
That documentation was for cljs, figwheel-main implementation for existing project. For this "Documentation for clj/cljs implementation for websockets #16" I'm creating a separate documentation.

**Comment by azureus89** [comment]
okay, got it :)

**Comment by azureus89** [comment]
@VikramShawFL do you want to refine this documentation based on experiences you've had with parikshith. When kavya migrates her code back to xtnt-micro - then you can see again if your documentation is clear enough.

**Comment by VikramShawFL** [comment]
I have already made some modification. As of now it is fine. If I find something important which should be added in the documentation I'll add then.

**Comment by azureus89** [comment]
but have those changes been merged into master? otherwise no one can see them :)

**Comment by VikramShawFL** [comment]
No, it's in vk-16-websocket branch in doc folder and I have created a pull request also

**Comment by azureus89** [comment]
this is closed for now ... will tackle specific implementations in separate issues
