### ISSUE TITLE
UI for posts / newsfeed page

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#17]

**Comment by ParikshithMohan** [comment]
Can you tell me what this newsfeed page should look like?

**Comment by ParikshithMohan** [comment]
i was thinking more like this page

http://preview.themeforest.net/item/ideabox-material-blogmagazine-html-template/full_screen_preview/21754529

**Comment by azureus89** [comment]
use twitter as reference

**Comment by ParikshithMohan** [comment]
This is what I have made.
![pk-newsfeed-17-1](https://user-images.githubusercontent.com/24820582/62942727-899ec900-bdf6-11e9-801b-13b27422a870.PNG)
![pk-newsfeed-17-2](https://user-images.githubusercontent.com/24820582/62942729-899ec900-bdf6-11e9-8428-293999717ad4.PNG)

**Comment by azureus89** [comment]
Much better than your previous dashboard ... look at making it more sleek ... there are many small things that you can improve, im sure you yourself can see that.

**Comment by azureus89** [comment]
whats with the silence ... 6 days since last update

**Comment by ParikshithMohan** [comment]
sorry working on it

**Comment by ParikshithMohan** [comment]
Improved newsfeed.

![improved-newsfeed-1](https://user-images.githubusercontent.com/24820582/63258673-30251700-c29a-11e9-9929-91a8e958b0fe.PNG)
![improved-newsfeed-2](https://user-images.githubusercontent.com/24820582/63258674-30bdad80-c29a-11e9-87a3-654fd26adcf1.PNG)

**Comment by azureus89** [comment]
What are the improvements .. what are you trying to improve .. what are the differences you see from the reference page that need more work

**Comment by ParikshithMohan** [comment]
**IMPROVEMENTS:**
1. Search bar added
2. removed overflow from both the divs in the right side container(Trending and you might like)
3. Added terms and conditions
4. People following the page added
5. Replaced 'compose' button with 'Create feed'  button in left container
6. Added comment, retweet, Like and dm icons under the feed.
7. Added date and expand icon in the feed.
8. Minor design flaws corrected(padding,borders and colors)


**IMPROVEMENT NEEDED:**
1. Right side container scrolling to be limited. So the 'trending now' and 'you might like' divs are constantly displayed while scrolling down.

3. Scrolling anywhere should only move the middle container(to display all the feeds) and a small portion of the right container. After reaching the end of the right container, the position of divs on the right container should be fixed and only middle container can be scrolled.

2. The icons under the feed(comment, like etc..) need to light up to specific colors. When not hovering they are grey but on hovering they need to change color. So on hover a colored variant of the same icon should replace the old one. I think js/cljs is needed for that.

**Comment by ParikshithMohan** [comment]
![image](https://user-images.githubusercontent.com/24820582/63415082-ca13cd80-c41a-11e9-98e0-4e6da01d913c.png)

**Comment by azureus89** [comment]
better but only slightly, attention to details please

**Comment by ParikshithMohan** [comment]
Having trouble starting repl. I created new branch from origin/master and then did the usual `lein run 8000`.That did not work.I also tried cider-jack-in .That started the localhost but did not load the page.

**Comment by ParikshithMohan** [comment]
@azureus89 @VikramShawFL Above.

**Comment by VikramShawFL** [comment]
@ParikshithMohan Use only ``lein run`` not ``lein run 8000`` as the port number is pre defined and then you can go to ``localhost:8000`` and see the websocket is running. You can run the cider along with ``lein run``

**Comment by VikramShawFL** [comment]
There are two ways to start the websocket:
1) with ``lein run``
2) with cider-jack-in:-  When you start the repl, all the code has loaded, but the server hasn't started yet, in order to start the server you have to go into the repl and run (-main) or whatever the main function is in your program that starts the app server. After this it works just like lein run, except when you change routing etc, it will update.

**Comment by ParikshithMohan** [comment]
@VikramShawFL Thanks.Its running.

**Comment by ParikshithMohan** [comment]
@azureus89 @VikramShawFL Changes made in hiccup while repl runs, cannot be seen..ie no changes are being reflected on the localhost screen, even when I refresh the page. To see the changes the repl needs to be restarted...which is very frustrating. Plus css files are not being recognized.

**Comment by VikramShawFL** [comment]
@ParikshithMohan How you are running the server?

**Comment by ParikshithMohan** [comment]
@VikramShawFL lein run

**Comment by VikramShawFL** [comment]
@ParikshithMohan Add this to namespace and in (-main) function in handler.clj to see the changes you are making after refreshing the page. ``wrap-reload`` is a ring middleware function that will push all our code changes to the application each time we save. 
![image](https://user-images.githubusercontent.com/46559614/63597376-efe7d080-c5da-11e9-9aa9-e9206ea30abe.png)
![image](https://user-images.githubusercontent.com/46559614/63597395-fbd39280-c5da-11e9-8a24-40152404456e.png)

**Comment by VikramShawFL** [comment]
@ParikshithMohan Error because of which your css was not working:-
1) in (include-css "newsfeed.css") there was typo error. You wrote newfeed.css
2) since your all css file are in css folder so you have to add path in your include-css like ``(include-css "css/newsfeed.css")``
3) you can add multiple css file in one include only.
Have commited to your repository, it is working please check

**Comment by azureus89** [comment]
@VikramShawFL dont push code to someone elses branch ... if you want to suggest code changes to them, just like with master ... create a new branch on their code, and send a pull request from your branch to their branch

**Comment by VikramShawFL** [comment]
okay, I'll keep in mind from next time.

**Comment by azureus89** [comment]
@ParikshithMohan branch naming convention mistake
should be pk-17-newsfeed

**Comment by ParikshithMohan** [comment]
Not able to push. I think its because vikram had pushed something to my branch earlier. @azureus89 

![image](https://user-images.githubusercontent.com/24820582/63765731-4d379680-c8e7-11e9-892e-7dd524369dae.png)

How to resolve?

**Comment by ParikshithMohan** [comment]
![image](https://user-images.githubusercontent.com/24820582/63765931-b9b29580-c8e7-11e9-8ce7-4c68da8265aa.png)

**Comment by ParikshithMohan** [comment]
![image](https://user-images.githubusercontent.com/24820582/63766031-f7172300-c8e7-11e9-9cf6-3fae5674b6e9.png)

The unpulled one is vikrams..(css fixed)

**Comment by VikramShawFL** [comment]
@ParikshithMohan First update your local repository and then push. It's clearly says that your local repository is not updated

> Not able to push. I think its because vikram had pushed something to my branch earlier. @azureus89
> 
> ![image](https://user-images.githubusercontent.com/24820582/63765731-4d379680-c8e7-11e9-892e-7dd524369dae.png)
> 
> How to resolve?

**Comment by ParikshithMohan** [comment]
@VikramShawFL Yes.But ill loose the work i have done till now right?

**Comment by VikramShawFL** [comment]
@ParikshithMohan I'm not sure about that. You can copy your work and paste it somewhere else and then you can update your local repository. After updating paste it back to your specific files

**Comment by ParikshithMohan** [comment]
@VikramShawFL yes thats what i initially thought of. Maybe @azureus89 knows a better way, instead of doing that...??

**Comment by azureus89** [comment]
@VikramShawFL this is why you shouldnt push to someone elses branch :)
@ParikshithMohan ... the git way is to use a stash, for future reference
but looking at the commit, vikrams changes are very small and you may get a merge conflict when you pull from origin but it will not be hard to resolve, its only 1/2 lines ... kavya is scheduling a call tonight for css review, we can do it in that call ... until then work on local, and post the updates via photos in these comments

**Comment by ParikshithMohan** [comment]
![1-2019090615-pk-17-newsfeedui](https://user-images.githubusercontent.com/24820582/64418294-5d562f80-d0b8-11e9-8cc2-c7ce9338b593.PNG)
![2-2019090615-pk-17-newsfeedui](https://user-images.githubusercontent.com/24820582/64418295-5d562f80-d0b8-11e9-99b2-edeef880a27a.PNG)
