### ISSUE TITLE
UI for chat page

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#18]

**Comment by kattakavya** [comment]
@azureus89 how should chat page look like? what all it should contain?Can you please elaborate it.

**Comment by azureus89** [comment]
Use discord as a reference

**Comment by kattakavya** [comment]
@azureus89
code
.dis
{
position: fixed;
height: 104px;
width: 104px;
left: -9px;
top: -12px;
border-radius: 50%;
z-index: 7;
}
.dis-back
{
border-radius: 50%;
height: 63px;
width: 63px;
top: 9px;
left: 12px;
position: fixed;
z-index:6;
background-color:#2f3136;
}
.dis-back:hover
{
background-color: rgb(114, 137, 218);
cursor: pointer;
}
problem:
hover effect is not working..i don't know were i have gone a mistake.

**Comment by azureus89** [comment]
ignore and proceed, we can resolve on a call sometime ... probably cant change color from hex value to rgb value ... try and see ... otherwise maybe some other conflict or issue in class naming in html ..

**Comment by kattakavya** [comment]
@azureus89 I have done part 1 &2 Css improvement, please find the snapshot and provide the feedback.

**Comment by kattakavya** [comment]
@azureus89 please find the snap-shot of UI chat and provide the feedback, if it get finalized i will merge the project into xtnt-micro

**Comment by azureus89** [comment]
wwe are not merging, we are re-doing in xtnt micro on top of the skeleton framework that is already there ... this may take some time, focus on trello issues on xtnt-micro
