### ISSUE TITLE
CouchDB Adapter

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#3]

**Comment by VikramShawFL** [comment]
Issue is with adding a data to database function i.e. ``doc-db``. I'm trying to executing this ```  (println (:out (sh "curl" "-H" "Content-Type: application/json" "-X" "POST" "http://127.0.0.1:5984/ram" "-d" '{"Company: " "Example, Inc"}')))```
Error:-```Syntax error reading source at (REPL:36:143).
Unmatched delimiter: )```
When I'm executing the same syntax in terminal, there it is working fine `` curl -H 'Content-Type: application/json' -X POST http://127.0.0.1:5984/ram  -d '{"company": "Example, Inc."}'``

**Comment by azureus89** [comment]
says unmatched delimiter, looks like error is with syntax somewhere in the program, im going through your gbranch right now

**Comment by azureus89** [comment]
Think its an issue with using single quotes ... have you tried alternative ways ... instead of the putting the body in single quotes, use double quotes outside and single quotes inside ... or use let to pre-store that as a string and then call the string inside the shell command?

**Comment by azureus89** [comment]
Because its a compile time error, not a run time error. Clojure isnt able to eval the function itself, its not running it and giving the error. Try this:
`(defn doc-db []
  (println (:out (sh "curl" "-H" "Content-Type: application/json" "-X" "POST" "http://127.0.0.1:5984/ram" "-d" "{'Company: ' 'Example, Inc'}"))))`

**Comment by VikramShawFL** [comment]
So I tried above code, it is giving me an error ``{"error":"bad_request","reason":"invalid_json"}``
Then I tried using let ```
(defn doc-db []
  (let [name "Super Co."]
  (println (:out (sh "curl" "-H" "Content-Type: application/json" "-X" "POST" "http://127.0.0.1:5984/ram" "-d" "name")))))```

I have used name variable without double quote also, but giving me the same error ``{"error":"bad_request","reason":"invalid_json"}``

**Comment by azureus89** [comment]
we both made a syntax error didnt notice. modified  code:
`(defn doc-db []
  (println (:out (sh "curl" "-H" "Content-Type: application/json" "-X" "POST" "http://127.0.0.1:5984/ram" "-d" "{'Company': 'Example, Inc'}"))))`


The separator for the json key value, we had put it inside the quotes in the clojure function. Stupid typo.

**Comment by azureus89** [comment]
the json inside sh is a standard json string ... not a clojure data structure, so it needs separators, {key1 : value1, key2: value2}

**Comment by VikramShawFL** [comment]
Yeah, that's what it is key1 is the Company and it's value is Example, Inc. I tried this yesterday only ``"{'Company': 'Example, Inc'}"`` It was giving me an error ``{"error":"bad_request","reason":"invalid_json"}``

**Comment by azureus89** [comment]
please try and show me

**Comment by VikramShawFL** [comment]
So I tried this 
```(defn doc-db [] (println (:out (sh "curl" "-H" "Content-Type: application/json" "-X" "POST" "http://127.0.0.1:5984/ram" "-d" "{'Company': 'Example, Inc'}"))))```
And the error is ``{"error":"bad_request","reason":"invalid_json"}``

**Comment by azureus89** [comment]
Ditch this, come back to it later, wasting time ... use http directly instead of using curl ... look for clojure http libraries

**Comment by azureus89** [comment]
shouldnt be hard ... whats happening

**Comment by VikramShawFL** [comment]
I got this library for CouchDB ``https://github.com/clojure-clutch/clutch`` So I have added the dependency ``[com.ashafa/clutch "0.4.0"]`` and then I have added ``(require '[com.ashafa.clutch :as couch])`` in the namespace but when I'm running the given example in repl it is showing error. I guess I'm not able to connect with my project.

**Comment by azureus89** [comment]
please report errors/handle faster .. whats the error

**Comment by VikramShawFL** [comment]
The error is with the namespace. When I'm executing this `` [environ.core :refer [env]]`` getting this error
```Execution error (FileNotFoundException) at xtnt-micro.core/eval16982$loading (form-init6989781727144421164.clj:10).
Could not locate environ/core__init.class, environ/core.clj or environ/core.cljc on classpath.```
Because of which when I'm executing ``(with-db (couch/get-document "blogs"))`` 
It gives me ``Syntax error compiling at (xtnt-micro:localhost:51429(clj)*:70:18).
Unable to resolve symbol: with-db in this context``

**Comment by azureus89** [comment]
push code, many references here i cant see ... what is environ.core?

**Comment by azureus89** [comment]
havent included environ in dependencies

> Now you can use this for the connection string:
> 
> (require '[com.ashafa.clutch :as couch])
> (require '[environ.core :refer [env]])
> 
> (define db (env :database-url))
> (couch/get-document db "home-page")
> You can find out more about using environment variables here: https://github.com/weavejester/environ
> 

and this line from profile clj is copy paste  :profiles/dev  {:env {:database-url "wiki"}})
you need to change to the name of your db locally once environ is in your project

**Comment by azureus89** [comment]
error is very clear 
Could not locate environ/core__init.class, environ/core.clj or environ/core.cljc on classpath.```

ie. dependency issue
how long have you been stuck on this?

**Comment by VikramShawFL** [comment]
I have created a database locally from Futon of name dev. 
About an hour I guess after that I was trying a different method from ``https://www.ibm.com/developerworks/java/library/j-couchdb-clojure/j-couchdb-clojure-pdf.pdf``
The libraries version are bit old but in this also I was having problem with the json namespace from List 2 ``(require ['clojure.contrib.json :as 'json])``.

**Comment by azureus89** [comment]
Do adapter first ... add environ etc and connect to the database ... if json is an issue, raise as separate issue ... and once you have demonstrated connection to couchdb ... read/write, this issue is closed ... json can be tackled after merging this to master in a separate issue

**Comment by VikramShawFL** [comment]
What does this ``:profiles/dev {:env {:database-url "wiki"}}`` means? Do I need to create profile.clj file
![Screen Shot 2019-07-19 at 6 02 22 PM](https://user-images.githubusercontent.com/46559614/61535288-890d4f80-aa4f-11e9-8f73-1b07a1223379.png)

**Comment by azureus89** [comment]
see the documentation for environ ... its from there ... its used to set environment variables, so that you dont have to keep calling them ... or refer to them in your code.

Good practice in clojure is to not directly refer to strings / numbers etc in the function itself ... keep the fuinctions functional ... and keep the data in data structures

so instead of (`get-document "customers" "vikram") `... this goes into a function ... where vikram is given to the function as a parameter when its called ... and customers is set as an environment variable ... and you get a pure function `(defn couch-read [cust] (get-document db cust))`

where you have defined db in your environment variable as "customers". clutch will then look the the "customers" database in couchdb when you call db.

which you can then call with `(get-document "vikram")`

you dont NEED environ ... its just good practice to not have to pepper the code with strings etc.

It also helps with security .. for instance a database password etc can then be set outside ... you may not want developers to see it in the code. Esp if you are working with outside collaborators etc.

**Comment by azureus89** [comment]
Also ... you already have a profiles.clj ... why are you asking if you need to create it?? confused.

**Comment by azureus89** [comment]
Need this for something, am working on this ... move to next issue

**Comment by azureus89** [comment]
I'm creating a bunch of helper libraries, they will be outside this library. This issue will be closed once i've integrated and tested them.

**Comment by azureus89** [comment]
closing this, moving to a different db stack
