### ISSUE TITLE
Clone trello UI

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#31]
Clone all elements on the trello board page, no clicks and popups, just the elements on the main board page. Dont make one big hiccup function, make it into components.

**Credits:** 20

**Comment by ParikshithMohan** [comment]
![trelloui](https://user-images.githubusercontent.com/24820582/64526560-45351900-d321-11e9-9317-e44814e37448.PNG)

So everything in here?

**Comment by azureus89** [comment]
yes just the UI, but make sure you are refactoring your hiccup and creating components, I dont want one big mess of hiccup code. If you dont know what I mean, when you do a little bit, notify me, ill re-factor and show you.
Functional UI will be driven by data state, so in case you didnt understand from the piano example, notify me when you progress a little bit and have a few things done, and ill show you.

**Comment by ParikshithMohan** [comment]
Having trouble dividing hiccup into different components. 
![image](https://user-images.githubusercontent.com/24820582/64528938-4ff2ac80-d327-11e9-9e24-ba38452ec4e6.png)

Highlighted : header and footer are the two different functions with hiccup.

This produces a syntax error

**Comment by azureus89** [comment]
please dont send me screenshots of code, screenshots are for UI

**Comment by azureus89** [comment]
in the routing you can refer to only one function ... you need to split up the hiccup code in your trello namespace and compile it into one function ... check html5-synth for this ... or any hiccup example, youll see how its done
 you cant call two functions when somebody lands on /trelloui
