### ISSUE TITLE
Clone trello popup

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#32]
Clone the popup that comes whenever you click a trello card.

**Comment by kattakavya** [comment]
@azureus89 you mean to say add card?
![image](https://user-images.githubusercontent.com/46553145/64699225-f4a8f180-d4c1-11e9-8a8f-57ea14c1689e.png)
is this should I prepare?

**Comment by azureus89** [comment]
@kattakavya no the popup that comes when you click a card on trello ... a card that already exists, where you can add comments etc

**Comment by azureus89** [comment]
closing this, not required any more
