### ISSUE TITLE
Form based write/edit interface

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#5]

**Comment by ParikshithMohan** [comment]
@azureus89 Does this involve HTML forms as the interface?

**Comment by azureus89** [comment]
Yes I need a mobile first nice interface for creating and editing database entries using forms.
Make the styles for classes and types of components easily readable, because I want this to be reused again and again.
Get a decent interface going first, give me components.
Demonstrate all form components working with hiccup.
Then we will close this issue and move onto 6.
We will create a new issue to refine UI and add themes etc.

For this issue I need simple forms, something I can build on top of.
I expect you wont be using a lot of best practices, ill point them out and suggest alternatives when i see it, other than that I will only tell you what I need, not going to fix your problems for you unless its a hack/trick that its unlikely you will find/know without experience.

Deploy first, find workarounds if you get stuck. Target and review is on Monday.
No details for now, so quickly submit a working model. During the review Ill point out what else you can add, and what variations are needed, and we will close.

important: mobile first

**Comment by ParikshithMohan** [comment]
@azureus89  Figwheel main not working while starting repl. It says Error in process filtering.figwheel-main is not available. Is it some other component?

**Comment by ParikshithMohan** [comment]
@azureus89 Also I cloned from the master. How are the html and css files created in the resource folder in html-synth project?

**Comment by azureus89** [comment]
oh yeah I forgot ... sorry ... this is a clojure project ... do it in clojure only.
Look up how to use hiccup directly in clojure.
Nothing is different ... css files go in resources folder, if its not there you have to create it.
Only difference is you have to create a route for the page where you are going to demo the form
localhost:xxx/forms
For this you use compojure ... defroutes app is the function vikram is using
You have to put one line there for create a new route .. check compojure documentation ... its very simple.

After that everything else is the same .. same old hiccup. clj/cljs works like nodejs you can code on server or browser with most libraries, no difference

**Comment by ParikshithMohan** [comment]
@azureus89 Do you want a sample of all the forms? What data do you want in them?

**Comment by azureus89** [comment]
All form elements first .. then we will see what else .. check bootstrap or any other css library for what that means

**Comment by azureus89** [comment]
Whats taking so long for moving into a different namespace etc?

**Comment by ParikshithMohan** [comment]
yeah sorry done.

**Comment by azureus89** [comment]
CSS?

**Comment by ParikshithMohan** [comment]
how do u want it?

**Comment by azureus89** [comment]
???????

> Yes I need a mobile first nice interface for creating and editing database entries using forms.
> Make the styles for classes and types of components easily readable, because I want this to be reused again and again.
> Get a decent interface going first, give me components.
> Demonstrate all form components working with hiccup.
> Then we will close this issue and move onto 6.
> We will create a new issue to refine UI and add themes etc.
> 
> For this issue I need simple forms, something I can build on top of.
> I expect you wont be using a lot of best practices, ill point them out and suggest alternatives when i see it, other than that I will only tell you what I need, not going to fix your problems for you unless its a hack/trick that its unlikely you will find/know without experience.
> 
> Deploy first, find workarounds if you get stuck. Target and review is on Monday.
> No details for now, so quickly submit a working model. During the review Ill point out what else you can add, and what variations are needed, and we will close.
> 
> important: mobile first

**Comment by azureus89** [comment]
Css has some flaws and can be more efficient ... we can address this later tonight if you're up ... You need to cover more comprehensively ... see bootstrap for reference:
https://getbootstrap.com/docs/4.0/components/forms/
Dont do everything, just pick the next set of things that you think are important from what they have covered. Your set is very basic.
More comprehensive set + efficient CSS + responsive = close of issue

**Comment by ParikshithMohan** [comment]
Comprehensive?

**Comment by ParikshithMohan** [comment]
You mean implement all the elements from that bootstrap link u sent?

**Comment by azureus89** [comment]
Read please:

> Css has some flaws and can be more efficient ... we can address this later tonight if you're up ... You need to cover more comprehensively ... see bootstrap for reference:
> https://getbootstrap.com/docs/4.0/components/forms/
**> Dont do everything, just pick the next set of things that you think are important from what they have covered. Your set is very basic.**
> More comprehensive set + efficient CSS + responsive = close of issue

**Comment by ParikshithMohan** [comment]
yeah got it...

**Comment by ParikshithMohan** [comment]
Don't know what to do with skeleton. Confused with what to do now. Tell me exactly what to do and the end result you're expecting, so I can finish the issue as soon as possible. Is it ok to use any technique i want to finish the task?

**Comment by azureus89** [comment]
The skeleton site has a download link which will give you the skeleton css files. You need to put that in resources, and refer to it in your html.

Use hiccup in clojure and show me all the skeleton elements you on that site working, they have shown you the code right under the elements, it should be very simple.

**Comment by azureus89** [comment]
I'm expecting to see a page that shows me a simple demo of all the form styles at the very least.
This would include forms in a grid, multiple coloumns etc. All shown on the skeleton site.

Right now I just want to see this - responsive css styles. That should close this issue.
like I said : More comprehensive set + efficient CSS + responsive = close of issue

**Comment by azureus89** [comment]
Okay this works ... let me check for any conflicts, and i will merge into master. Once its done, ill assign next issue to you on the dev support channel.

**Comment by azureus89** [comment]
Submit pull request please
