### ISSUE TITLE
Table based view entries and user dashboard boilerplate

### ISSUE THREAD

**Issue by azureus89** [224-1/xtnt-micro#6]

**Comment by ParikshithMohan** [comment]
So the table based view can be done from skeleton CSS. I don't know what user dashboard boilerplate is. What do I do in that?

**Comment by azureus89** [comment]
Dashboard references : https://wrapbootstrap.com/search?q=dashboard

ignore the chart elements. The rest. Pick a simple one ... header, menu, blocks displaying things in different colours etc. But the table you've done into the dashboard

**Comment by ParikshithMohan** [comment]
You mean *put right?

**Comment by ParikshithMohan** [comment]
When I put the laptop on sleep...the css file gets frozen...the style is fixed and cannot be changed even after restarting the repl and the shell. The new css file is also acting like the dashboard.css file.

**Comment by ParikshithMohan** [comment]
Ever since i tried merging cljs and clj...im facing all these problems...Dont know where exactly the problem is...

**Comment by ParikshithMohan** [comment]
i found a hack...so if i make the changes, close and reopen my laptop...the changes are being reflected.

**Comment by azureus89** [comment]
Shouldnt have done cljs / clj merging on this branch ... it is a separate issue for a reason no ...

**Comment by azureus89** [comment]
What is going wrong here ... why are you unable to close this issue?

**Comment by azureus89** [comment]
whats going wrong ...

**Comment by azureus89** [comment]
> i found a hack...so if i make the changes, close and reopen my laptop...the changes are being reflected.

cool story ... but if this is an issue with the repl / emacs / project config ... this needs to be an issue in itself also

**Comment by ParikshithMohan** [comment]
> > i found a hack...so if i make the changes, close and reopen my laptop...the changes are being reflected.
> 
> cool story ... but if this is an issue with the repl / emacs / project config ... this needs to be an issue in itself also

This issue is a nightmare because i dont know where the source of the problem is. Back when i was doing it , i deleted all the css files to check if the designs i made would go away... nothing changed  when i did that. So i had to create all the block elements in between the navbar and sidebar that i had created earlier...the navbar and sidebar design was unchangable...

**Comment by ParikshithMohan** [comment]
pk-6-dash is the branch I want to merge...Dont want the other 2 simillar looking branches.

**Comment by azureus89** [comment]
Make an issue for REPL nightmare please, told you be lazy ... blame whatever is going on. But also css files are there ... so you can technically still show methe code working without thre repl etc. So show me that, alongside making an issue that details what needs fixing on the repl issue or whatever that issue is.

on branches ... delete all other branches that dont matter. And send a pull request from the branch that you want to merge in only.

**Comment by ParikshithMohan** [comment]
![image](https://user-images.githubusercontent.com/24820582/62348872-bb24b400-b51b-11e9-81e1-af38169bc4f4.png)

I have no idea what to do now...

**Comment by azureus89** [comment]
@ParikshithMohan status on this issue?
